In [1]:
import geopandas as gpd

blocks_gdf = gpd.read_parquet('./../data/blocks.parquet')
blocks_gdf.head()

,geometry,land_use,is_living,build_floor_area,living_demand,living_area,share_living,business_area,share_business,site_area,...,capacity_bus_station,capacity_bus_stop,capacity_pier,capacity_animal_shelter,capacity_military_kom,capacity_prison,capacity_landfill,capacity_plant_nursery,capacity_greenhouse_complex,capacity_warehouse
id,,,,,,,,,,,,,,,,,,,,,
0,"POLYGON ((354918.622 6625258.829, 354901.464 6...",None,True,43840.686518,50.641057,30688.480678,2.199357,13152.205840,0.942581,8.044667e+05,...,0,0,0,0,0,0,0,0,0,0
1,"POLYGON ((355412.142 6623378.149, 355411.700 6...",transport,True,10294.395525,53.114392,2177.690063,0.431105,8116.705462,1.606820,2.317313e+04,...,0,0,0,0,0,0,0,0,0,0
2,"POLYGON ((353934.329 6625429.433, 353923.453 6...",recreation,True,1173.871643,58.693582,821.710142,0.706252,352.161501,0.302679,3.630058e+05,...,0,0,0,0,0,0,0,0,0,0
3,"POLYGON ((355099.099 6623847.765, 355074.808 6...",residential,True,46303.954706,52.660044,30595.485797,2.760046,15708.468909,1.417075,1.964145e+05,...,0,0,0,0,0,0,0,0,0,0
4,"POLYGON ((352766.168 6621954.748, 352744.412 6...",recreation,True,153749.574111,53.097680,106407.750936,2.352959,47341.823175,1.046854,1.781752e+06,...,0,0,0,0,0,0,0,0,0,0

## Development indicators

In [2]:
from blocksnet.analysis.indicators.development import calculate_development_indicators

blocks_df = calculate_development_indicators(blocks_gdf[[
    'site_area',
    'footprint_area',
    'build_floor_area',
    'living_area'
]])

2025-02-25 23:56:19.466 | WARNING  | blocksnet.analysis.indicators.development.core:_restore_population:22 - The population is not in columns, restoring
2025-02-25 23:56:19.468 | WARNING  | blocksnet.analysis.indicators.development.core:_restore_business_area:29 - The business_area is not in columns, restoring

In [3]:
blocks_df

,site_area,footprint_area,build_floor_area,living_area,business_area,population,fsi,gsi,mxi,l,osr,share_living,living_demand
id,,,,,,,,,,,,,
0,8.044667e+05,13953.390266,43840.686518,30688.480678,13152.205840,1534,0.054497,0.017345,0.700000,3.141938,18.031500,2.199357,20.005528
1,2.317313e+04,5051.410558,10294.395525,2177.690063,8116.705462,108,0.444238,0.217986,0.211541,2.037925,1.760348,0.431105,20.163797
2,3.630058e+05,1163.480697,1173.871643,821.710142,352.161501,41,0.003234,0.003205,0.700000,1.008931,308.246934,0.706252,20.041711
3,1.964145e+05,11085.135352,46303.954706,30595.485797,15708.468909,1529,0.235746,0.056437,0.660753,4.177121,4.002452,2.760046,20.010128
4,1.781752e+06,45222.959595,153749.574111,106407.750936,47341.823175,5320,0.086291,0.025381,0.692085,3.399812,11.294526,2.352959,20.001457
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16315,6.477731e+03,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,NaN,NaN,inf,NaN,NaN
16316,1.211677e+03,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,NaN,NaN,inf,NaN,NaN
16317,1.835190e+04,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,NaN,NaN,inf,NaN,NaN
16318,1.592307e+03,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,NaN,NaN,inf,NaN,NaN
16319,1.068911e+06,65469.613038,108402.558382,39359.099854,69043.458529,1967,0.101414,0.061249,0.363083,1.655769,9.256625,0.601181,20.009710