In [5]:
import geopandas as gpd

blocks = gpd.read_file('blocks.geojson')[['geometry']]
blocks

/home/vasilstar/masterplanning/.venv/lib/python3.10/site-packages/pyogrio/raw.py:198: RuntimeWarning: Several features with id = 218 have been found. Altering it to be unique. This warning will not be emitted anymore for this layer
  return ogr_read(

                                               geometry
0     MULTIPOLYGON (((349424.859 6631180.891, 349424...
1     MULTIPOLYGON (((352083.617 6633950.146, 352240...
2     MULTIPOLYGON (((346700.642 6618453.176, 346681...
3     MULTIPOLYGON (((347043.363 6618261.219, 347042...
4     MULTIPOLYGON (((354879.039 6618859.116, 354845...
...                                                 ...
9377  MULTIPOLYGON (((346635.461 6647492.048, 346473...
9378  MULTIPOLYGON (((346361.221 6647603.446, 346328...
9379  MULTIPOLYGON (((344109.285 6649134.367, 344000...
9380  MULTIPOLYGON (((346323.488 6649497.386, 346199...
9381  MULTIPOLYGON (((346670.461 6649890.747, 346543...

[9382 rows x 1 columns]

In [6]:
from blocksnet.blocks.postprocessing import postprocess_urban_blocks

postprocess_urban_blocks(blocks)

                                               geometry
0     POLYGON ((349424.859 6631180.891, 349424.751 6...
1     POLYGON ((352083.617 6633950.146, 352240.448 6...
2     POLYGON ((346700.642 6618453.176, 346681.107 6...
3     POLYGON ((347043.363 6618261.219, 347042.608 6...
4     POLYGON ((354879.039 6618859.116, 354845.405 6...
...                                                 ...
9597  POLYGON ((356638.451 6623610.759, 356647.189 6...
9598  POLYGON ((357828.934 6622732.206, 358060.798 6...
9599  POLYGON ((348518.331 6635309.076, 348290.092 6...
9600  POLYGON ((336126.984 6638616.257, 336091.806 6...
9601  POLYGON ((332513.041 6639516.665, 332514.198 6...

[9602 rows x 1 columns]