In [1]:
import geopandas as gpd

blocks = gpd.read_parquet('./../data/blocks.parquet')
columns = [c for c in blocks.columns if 'capacity_' in c]
blocks = blocks[['geometry', 'population', 'site_area', *columns]].copy()
blocks.head(3)

,geometry,population,site_area,capacity_convenience,capacity_cafe,capacity_mall,capacity_pharmacy,capacity_bank,capacity_fuel,capacity_pitch,...,capacity_bus_station,capacity_bus_stop,capacity_pier,capacity_animal_shelter,capacity_military_kom,capacity_prison,capacity_landfill,capacity_plant_nursery,capacity_greenhouse_complex,capacity_warehouse
id,,,,,,,,,,,,,,,,,,,,,
0,"POLYGON ((354918.622 6625258.829, 354901.464 6...",606,804466.712114,208.0,406.0,2216.0,474.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,"POLYGON ((355412.142 6623378.149, 355411.700 6...",41,23173.129862,811.0,0.0,0.0,0.0,148.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,"POLYGON ((353934.329 6625429.433, 353923.453 6...",14,363005.815802,0.0,0.0,0.0,0.0,0.0,501.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
import pandas as pd

accessibility_matrix = pd.read_pickle('./../data/accessibility_matrix.pickle')
accessibility_matrix.head()

,0,1,2,3,4,5,6,7,8,9,...,16310,16311,16312,16313,16314,16315,16316,16317,16318,16319
0,0.000000,18.718750,9.234375,17.21875,30.296875,27.390625,30.671875,23.281250,78.6875,81.2500,...,76.5625,102.5625,97.5000,132.250,130.8750,142.125,247.625,228.625,247.625,124.6250
1,17.859375,0.000000,19.015625,7.65625,20.281250,25.250000,25.234375,15.765625,76.8750,79.4375,...,74.6875,100.7500,95.6875,130.500,129.0000,140.250,245.875,226.875,245.875,112.5000
2,9.234375,20.796875,0.000000,20.21875,27.968750,25.062500,28.343750,20.953125,71.8750,74.4375,...,69.7500,95.8125,90.6875,125.500,124.0625,135.375,240.875,221.875,240.875,124.6250
3,15.937500,7.449219,18.421875,0.00000,21.109375,24.984375,27.781250,16.593750,76.3125,78.8125,...,74.1250,100.1875,95.0625,129.875,128.5000,139.750,245.250,226.250,245.250,113.3750
4,31.906250,19.765625,31.734375,21.28125,0.000000,21.781250,23.125000,15.429688,89.5625,92.1250,...,87.4375,113.5000,108.3750,143.125,141.7500,153.000,258.500,239.500,258.500,108.3125

## Simulated annealing

In [9]:
from blocksnet.enums import LandUse

blocks_lus = {
    # 1 : LandUse.INDUSTRIAL,
    # 2 : LandUse.RECREATION,
    1536 : LandUse.RESIDENTIAL
}

service_types = {
    "kindergarten": 0.2,
    "school": 0.2,
    "pharmacy": 0.2,
    "polyclinic": 0.3,
    "convenience": 0.2,   
    "cafe": 0.15,
    "playground": 0.2,
    "post": 0.1,
    "hairdresser": 0.1
}

In [10]:
from blocksnet.optimization.services import ServicesOptimizer

so = ServicesOptimizer(blocks[['site_area', 'population']], accessibility_matrix)

for service_type, weight in service_types.items():
    so.add_service_type(service_type, weight, blocks.rename(columns={f'capacity_{service_type}': 'capacity'})[['capacity']])

so.service_types

{'kindergarten': 0.2,
 'school': 0.2,
 'pharmacy': 0.2,
 'polyclinic': 0.3,
 'convenience': 0.2,
 'cafe': 0.15,
 'playground': 0.2,
 'post': 0.1,
 'hairdresser': 0.1}

In [11]:
variables_df, objective_value = so.run(blocks_lus, iterations=1000)

2025-03-24 04:52:50.744 | INFO     | blocksnet.optimization.services.core:_initialize_provisions_dfs:56 - Initial provision assessment
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 9/9 [02:26<00:00, 16.32s/it]
2025-03-24 04:55:17.638 | INFO     | blocksnet.optimization.services.core:run:153 - Starting the optimization process
obj :  1.30:  31%|â–ˆâ–ˆâ–ˆ       | 308/1000 [00:22<00:50, 13.71it/s]
2025-03-24 04:55:40.113 | SUCCESS  | blocksnet.optimization.services.core:run:160 - Optimization ended with objective value of 1.3

In [19]:
variables_df

,block_id,service_type,capacity,site_area,build_floor_area,count,total_capacity,total_site_area,total_build_floor_area
0,1536,school,250,18500.0,2500.0,0,0,0.0,0.0
1,1536,school,300,15000.0,2400.0,0,0,0.0,0.0
2,1536,school,600,30000.0,4800.0,1,600,30000.0,4800.0
3,1536,school,1100,33000.0,6600.0,2,2200,66000.0,13200.0
4,1536,school,250,200.0,2200.0,0,0,0.0,0.0
5,1536,school,300,300.0,3600.0,1,300,300.0,3600.0
6,1536,school,600,600.0,7100.0,0,0,0.0,0.0
7,1536,kindergarten,80,3520.0,240.0,2,160,7040.0,480.0
8,1536,kindergarten,180,6840.0,540.0,1,180,6840.0,540.0
9,1536,kindergarten,320,12160.0,960.0,1,320,12160.0,960.0
10,1536,kindergarten,80,250.0,180.0,0,0,0.0,0.0
11,1536,kindergarten,180,300.0,320.0,0,0,0.0,0.0
12,1536,kindergarten,320,320.0,600.0,1,320,320.0,600.0
13,1536,polyclinic,100,850.0,700.0,1,100,850.0,700.0
14,1536,polyclinic,150,1400.0,1050.0,0,0,0.0,0.0
15,1536,polyclinic,250,2000.0,1750.0,1,250,2000.0,1750.0
16,1536,polyclinic,500,4000.0,3500.0,0,0,0.0,0.0
17,1536,polyclinic,50,125.0,400.0,1,50,125.0,400.0
18,1536,polyclinic,100,150.0,700.0,3,300,450.0,2100.0
19,1536,convenience,50,30.0,25.0,3,150,90.0,75.0
20,1536,convenience,100,65.0,50.0,0,0,0.0,0.0
21,1536,convenience,160,80.0,130.0,1,160,80.0,130.0
22,1536,convenience,50,50.0,25.0,2,100,100.0,50.0
23,1536,convenience,100,50.0,50.0,2,200,100.0,100.0
24,1536,convenience,180,50.0,75.0,3,540,150.0,225.0
25,1536,playground,20,50.0,0.0,1,20,50.0,0.0
26,1536,playground,28,70.0,0.0,0,0,0.0,0.0
27,1536,playground,45,100.0,0.0,1,45,100.0,0.0
28,1536,pharmacy,30,40.0,30.0,3,90,120.0,90.0
29,1536,pharmacy,50,63.0,50.0,0,0,0.0,0.0
30,1536,pharmacy,70,85.0,70.0,5,350,425.0,350.0
31,1536,pharmacy,20,50.0,25.0,0,0,0.0,0.0
32,1536,pharmacy,40,95.0,40.0,1,40,95.0,40.0
33,1536,pharmacy,60,140.0,60.0,2,120,280.0,120.0
34,1536,cafe,25,100.0,75.0,2,50,200.0,150.0
35,1536,cafe,45,150.0,135.0,2,90,300.0,270.0
36,1536,cafe,65,200.0,150.0,1,65,200.0,150.0
37,1536,cafe,90,300.0,250.0,3,270,900.0,750.0
38,1536,cafe,30,200.0,90.0,5,150,1000.0,450.0
39,1536,cafe,50,350.0,150.0,6,300,2100.0,900.0
40,1536,cafe,70,500.0,200.0,0,0,0.0,0.0
41,1536,cafe,100,700.0,300.0,2,200,1400.0,600.0
42,1536,hairdresser,20,600.0,0.0,7,140,4200.0,0.0
43,1536,hairdresser,40,1000.0,0.0,2,80,2000.0,0.0
44,1536,hairdresser,100,3000.0,0.0,0,0,0.0,0.0
45,1536,hairdresser,20,250.0,400.0,2,40,500.0,800.0
46,1536,hairdresser,40,300.0,800.0,3,120,900.0,2400.0
47,1536,post,40,50.0,200.0,5,200,250.0,1000.0
48,1536,post,60,60.0,240.0,0,0,0.0,0.0
49,1536,post,80,100.0,320.0,4,320,400.0,1280.0